name: Python Application Test with Github Actions 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.12.7
        uses: actions/setup-python@v1
        with: 
          python-version: 3.12.7
      - name: Set up Environment Variables
        run: |
              echo "SERVER_HOSTNAME=${{ secrets.SERVER_HOSTNAME }}" >> $GITHUB_ENV
              echo "HTTP_PATH=${{ secrets.HTTP_PATH }}" >> $GITHUB_ENV
              echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> $GITHUB_ENV
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: extract 
        run: make extract 
      - name: transform
        run: make transform
      - name: query
        run: make query
      - name: test
        run: make test
      - name: format
        run: make format
